/*
Copyright 2021 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/
package controllers

import (
	"context"
	"reflect"

	"github.com/AbsaOSS/k8gb/controllers/internal/utils"

	k8gbv1beta1 "github.com/AbsaOSS/k8gb/api/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	gateway "sigs.k8s.io/gateway-api/apis/v1alpha1"
)

func (r *GslbReconciler) processGateway(gslb *k8gbv1beta1.Gslb) error {
	gw, err := r.gslbGateway(gslb)
	if err != nil {
		return err
	}

	return r.saveGateway(gslb, gw)
}
func (r *GslbReconciler) gslbGateway(gslb *k8gbv1beta1.Gslb) (*gateway.Gateway, error) {
	metav1.SetMetaDataAnnotation(&gslb.ObjectMeta, strategyAnnotation, gslb.Spec.Strategy.Type)
	if gslb.Spec.Strategy.PrimaryGeoTag != "" {
		metav1.SetMetaDataAnnotation(&gslb.ObjectMeta, primaryGeoTagAnnotation, gslb.Spec.Strategy.PrimaryGeoTag)
	}
	gw := &gateway.Gateway{
		ObjectMeta: metav1.ObjectMeta{
			Name:        gslb.Name,
			Namespace:   gslb.Namespace,
			Annotations: gslb.Annotations,
		},
		Spec: gslb.Spec.Gateway,
	}

	err := controllerutil.SetControllerReference(gslb, gw, r.Scheme)
	if err != nil {
		return nil, err
	}
	return gw, err
}

func (r *GslbReconciler) saveGateway(instance *k8gbv1beta1.Gslb, i *gateway.Gateway) error {
	found := &gateway.Gateway{}
	err := r.Get(context.TODO(), types.NamespacedName{
		Name:      instance.Name,
		Namespace: instance.Namespace,
	}, found)
	if err != nil && errors.IsNotFound(err) {

		// Create the service
		log.Info().Msgf("Creating a new Gateway, Gateway.Namespace %s, Gateway.Name: %s", i.Namespace, i.Name)
		err = r.Create(context.TODO(), i)

		if err != nil {
			// Creation failed
			log.Err(err).Msgf("Failed to create new Gateway Gateway.Namespace: %s, Gateway.Name: %s",
				i.Namespace, i.Name)
			return err
		}
		// Creation was successful
		return nil
	} else if err != nil {
		// Error that isn't due to the service not existing
		log.Err(err).Msg("Failed to get Gateway")
		return err
	}

	// Update existing object with new spec and annotations
	if !gatewayEqual(found, i) {
		found.Spec = i.Spec
		found.Annotations = utils.MergeAnnotations(found.Annotations, i.Annotations)
		err = r.Update(context.TODO(), found)
		if errors.IsConflict(err) {
			log.Info().Msgf("Gateway has been modified outside of controller, retrying reconciliation"+
				"Gateway.Namespace %s, Gateway.Name: %s", found.Namespace, found.Name)
			return nil
		}
		if err != nil {
			// Update failed
			log.Err(err).Msgf("Failed to update Gatwat Gateway.Namespace %s, Gateway.Name: %s",
				found.Namespace, found.Name)
			return err
		}
	}

	return nil
}

func gatewayEqual(gw1 *gateway.Gateway, gw2 *gateway.Gateway) bool {
	for k, v := range gw2.Annotations {
		if gw1.Annotations[k] != v {
			return false
		}
	}
	return reflect.DeepEqual(gw1.Spec, gw2.Spec)
}
